apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name}}
  ports:
    - name: portal
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: jboss
      protocol: TCP
      port: 9990
      targetPort: 9990
