app:
  name: deducciones
  replicaCount: 1
  image:
    owner: joaquinsolari
    repository: deducciones
    tag: 352 #TODO: cambiar por el tag de la imagen (ver en pipeline)
secret:
  configjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImFtOWhjWFZwYm5OdmJHRnlhVHBrYjJOclpYSXhOakE0IgogICAgICAgICAgICAgICAgfQogICAgICAgIH0KfQo=
